{% set name = "mosaic" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mosaic/archive/{{ version }}.tar.gz
  sha256: 8322e576eaa4f4ee020ad4ab133692e13838746a0c11051d93b4f240efe6d3a9

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - cartopy
    - cmocean
    - h5netcdf
    - netcdf4
    - matplotlib-base
    - numpy
    - pooch
    - pyproj
    - scipy
    - tqdm
    - xarray

test:
  imports:
    - mosaic
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/mosaic/
  summary: Graphics package for MPAS meshes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.e3sm.org/mosaic/
  dev_url: https://github.com/E3SM-Project/mosaic/

extra:
  recipe-maintainers:
    - andrewdnolan
    - xylar
