{% set name = "mosaic" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mosaic/archive/{{ version }}.tar.gz
  sha256: c3c1bde8ae3e3169cbd26a6659d8618ac7520b308a040c428c59dfc53d6c637f

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cartopy
    - cmocean
    - h5netcdf
    - netcdf4
    - matplotlib-base
    - numpy
    - pyproj
    - scipy
    - xarray

test:
  imports:
    - mosaic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/mosaic/
  summary: Graphics package for MPAS meshes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.e3sm.org/mosaic/
  dev_url: https://github.com/E3SM-Project/mosaic/

extra:
  recipe-maintainers:
    - andrewdnolan
    - xylar
