{% set name = "mosaic" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mosaic/archive/{{ version }}.tar.gz
  sha256: d0aaa7d12e0e68fef8b8acededf77d56e97f488fae32cce70770f74f42f897d8

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - cartopy <=0.24.0
    - cmocean
    - h5netcdf
    - netcdf4
    - matplotlib-base
    - numpy
    - pooch
    - pyproj
    - scipy
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - mosaic
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/mosaic/
  summary: Graphics package for MPAS meshes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.e3sm.org/mosaic/
  dev_url: https://github.com/E3SM-Project/mosaic/

extra:
  recipe-maintainers:
    - andrewdnolan
    - xylar
